package com.example.util

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val nativeName: String,
    val flag: String,
    val isRtl: Boolean = false
) {
    ENGLISH("en", "English", "English", "🇺🇸", false),
    ARABIC("ar", "Arabic", "العربية", "🇸🇦", true),
    FRENCH("fr", "French", "Français", "🇫🇷", false)
}

object AppStrings {
    fun get(key: String, language: AppLanguage): String {
        return when (language) {
            AppLanguage.ARABIC -> arabicStrings[key] ?: englishStrings[key] ?: key
            AppLanguage.FRENCH -> frenchStrings[key] ?: englishStrings[key] ?: key
            AppLanguage.ENGLISH -> englishStrings[key] ?: key
        }
    }

    private val englishStrings = mapOf(
        "app_name" to "A-Hex streak",
        "tab_library" to "Library",
        "tab_local_space" to "Local Space",
        "tab_streak" to "Streak",
        "tab_highlights" to "Highlights",
        "tab_discover" to "Discover",
        "tab_settings" to "Settings",
        
        // Search & Library
        "search_hint" to "Search books, authors, genres...",
        "search_trusted_title" to "Online Book Search (Noor Book & Gutenberg)",
        "search_trusted_desc" to "Search www.noor-book.com for Arabic books and https://www.gutenberg.org/ for English literature.",
        "search_noor_book" to "Noor Book (مكتبة نور)",
        "search_gutenberg" to "Project Gutenberg (gutenberg.org)",
        "import_book" to "Import Document",
        "import_book_desc" to "Add EPUB, PDF, or TXT from your device storage",
        "empty_library_title" to "Your Library is Empty",
        "empty_library_desc" to "Tap below to import your own EPUB, PDF, or TXT books, or explore classic literature.",
        "explore_catalog" to "Explore Catalog",
        "delete_book" to "Delete Book",
        "delete_book_confirm" to "Are you sure you want to remove this book from your library?",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "filter_all" to "All Formats",
        "filter_pdf" to "PDF",
        "filter_epub" to "EPUB",
        "filter_txt" to "TXT",
        "sort_recent" to "Recently Read",
        "sort_title" to "Title (A-Z)",
        "sort_progress" to "Highest Progress",

        // Settings & Storage
        "language_title" to "Language / اللغة / Langue",
        "language_desc" to "Select your preferred application display language.",
        "storage_title" to "Storage & Database",
        "installed_books" to "Installed Books in Library",
        "saved_highlights" to "Total Saved Highlights",
        "offline_cache" to "Offline Local Cache",
        "features_title" to "Included Engine Features",
        "speed_reader" to "RSVP Speed Reader",
        "ai_assistant" to "Smart Reading Assistant",
        "reading_streak" to "A-HEX READING STREAK",
        "active_habit" to "Active Habit",
        "open_in_browser" to "Search Online",
        "direct_pdf_download" to "Download PDF",
        "trusted_badge" to "Verified Public Domain & Open Access",
        "reading_mode" to "Reading Mode",
        "mode_light" to "Light",
        "mode_sepia" to "Sepia",
        "mode_dark" to "Dark",
        "theme_palette" to "Theme Palette",
        "daily_goal_title" to "Daily Reading Goal",
        "daily_goal_desc" to "Set your target minutes of reading per day to build your streak.",
        "export_backup" to "Export Backup",
        "restore_backup" to "Restore Backup",
        "share_progress" to "Share Progress",
        "streak_zero_title" to "Ready to start your streak!",
        "streak_zero_desc" to "Read today to begin your day 1 reading streak.",

        // TTS & Audio
        "tts_title" to "Text to Speech Voice Reader",
        "tts_initializing" to "Initializing Voice Engine...",
        "tts_ready" to "Voice Engine Ready",
        "tts_playing" to "Reading aloud...",
        "tts_paused" to "Voice paused",
        "tts_unsupported" to "Language not supported by current TTS engine.",
        "tts_missing_data" to "Voice data missing. Please download voice data in Android settings.",
        "tts_open_settings" to "Open TTS Settings",
        "tts_error" to "TTS Playback Error",
        "tts_speed" to "Voice Speed",

        // RSVP Speed Reader
        "rsvp_title" to "RSVP Speed Reader",
        "rsvp_wpm" to "WPM",
        "rsvp_word_count" to "Word %1\$d of %2\$d",
        "rsvp_time_left" to "~%1\$s left",
        "rsvp_back_20" to "Back 20 words",
        "rsvp_forward_20" to "Forward 20 words",
        "rsvp_page" to "Pg %1\$d/%2\$d",

        // Smart Face Presence Counter (Privacy-First)
        "face_presence_title" to "Smart Face-Assisted Reading Presence",
        "face_presence_desc" to "Privacy-first on-device camera presence estimation. Pauses streak counter if you look away. Never saves images or transmits biometric data.",
        "face_presence_enabled" to "Face Reading Presence Enabled",
        "face_presence_attentive" to "Reading Active (Face Detected)",
        "face_presence_candidate" to "Detecting Face...",
        "face_presence_no_face" to "No Face (Timer Paused)",
        "face_presence_multi_faces" to "Multiple Faces Detected",
        "face_presence_permission_required" to "Camera permission required for face-presence reading time.",
        "face_presence_camera_unavailable" to "Camera currently unavailable",
        "face_presence_disclaimer" to "Note: Estimates attention presence on-device only. Does not guarantee reading comprehension.",
        "face_privacy_badge" to "100% On-Device & Zero Image Storage",

        // Custom Voice Narrator Profile
        "voice_narrator_title" to "Custom Voice Narrator Studio",
        "voice_narrator_desc" to "Train your own personalized AI Voice Profile to narrate books in your unique vocal timbre, cadence, and pitch.",
        "voice_narrator_train_btn" to "Train Custom Voice Narrator",
        "voice_narrator_active" to "Cloned Voice Active",
        "voice_narrator_system" to "System Voice Active",

        // PDF Extraction Quality
        "pdf_scanned_notice" to "Scanned / Image-Only PDF: Text operations (TTS, RSVP, Search) may be limited.",
        "pdf_high_quality" to "Searchable Text PDF",

        // Common Reader Actions
        "chapter_toc" to "Table of Contents",
        "notes_and_highlights" to "Notes & Highlights",
        "font_size" to "Font Size",
        "line_spacing" to "Line Spacing",
        "export_epub" to "Convert & Export EPUB",
        "ambient_sounds" to "Ambient Reading Soundscapes",
        "vocab_vault" to "Vocabulary Vault",
        "mind_map" to "Chapter Mind Map",
        "book_reviews" to "Reviews & Discussion",

        // Interactive Onboarding & Tutorial
        "onboarding_skip" to "Skip",
        "onboarding_next" to "Next",
        "onboarding_back" to "Back",
        "onboarding_get_started" to "Begin Reading Journey",
        "onboarding_start_tutorial" to "Launch Interactive Tour",
        "onboarding_welcome_title" to "Empower Your Daily Reading",
        "onboarding_welcome_subtitle" to "The distraction-free, 100% offline e-reader designed to build unbreakable reading streaks across PDF, EPUB, and TXT documents.",
        "onboarding_habit_title" to "Set Your Daily Reading Habit",
        "onboarding_habit_subtitle" to "Choose your daily goal. Consistent small daily sessions compound into dozens of books every year.",
        "onboarding_features_title" to "Experience Interactive Tools",
        "onboarding_features_subtitle" to "Try our built-in RSVP rapid speed reader, adaptive reading themes, and acoustic voice narrator right now.",
        "onboarding_genres_title" to "Choose Your Literary Interests",
        "onboarding_genres_subtitle" to "Personalize your starter shelf with the genres you love most.",
        "tutorial_title" to "Interactive Walkthrough",
        "tutorial_step1_title" to "Universal Library Engine",
        "tutorial_step1_desc" to "Access your EPUB, PDF, and TXT books offline. Filter by format, search instantly, and import files from your device.",
        "tutorial_step2_title" to "A-Hex Reading Streak & Quests",
        "tutorial_step2_desc" to "Every minute of attentive reading powers your daily streak. Earn Streak Shields and complete reading quests.",
        "tutorial_step3_title" to "RSVP Speed Reading & Narration",
        "tutorial_step3_desc" to "Accelerate comprehension with RSVP rapid word flashing, or relax with natural Text-to-Speech audio reading.",
        "tutorial_step4_title" to "Voice Studio & Privacy First",
        "tutorial_step4_desc" to "Train a personalized voice profile to read books aloud. 100% on-device processing with zero cloud data tracking.",
        "settings_replay_onboarding" to "Replay Onboarding Flow",
        "settings_replay_tutorial" to "Interactive Feature Tour"
    )

    private val arabicStrings = mapOf(
        "app_name" to "A-Hex streak",
        "tab_library" to "المكتبة",
        "tab_local_space" to "المساحة المحلية",
        "tab_streak" to "الإنجاز",
        "tab_highlights" to "الاقتباسات",
        "tab_discover" to "استكشاف",
        "tab_settings" to "الإعدادات",

        // Search & Library
        "search_hint" to "ابحث عن كتب، مؤلفين، تصنيفات...",
        "search_trusted_title" to "بحث الكتب أونلاين (مكتبة نور وغوتنبرغ)",
        "search_trusted_desc" to "ابحث في مكتبة نور (www.noor-book.com) للكتب العربية ومشروع غوتنبرغ (gutenberg.org) للأدب العالمي.",
        "search_noor_book" to "مكتبة نور (noor-book.com)",
        "search_gutenberg" to "مشروع غوتنبرغ (gutenberg.org)",
        "import_book" to "استيراد مستند",
        "import_book_desc" to "إضافة ملفات EPUB أو PDF أو TXT من ذاكرة الجهاز",
        "empty_library_title" to "مكتبتك فارغة حالياً",
        "empty_library_desc" to "اضغط أدناه لاستيراد كتبك بصيغ EPUB أو PDF أو TXT، أو تصفح الكلاسيكيات المتاحة.",
        "explore_catalog" to "استكشاف الكتالوج",
        "delete_book" to "حذف الكتاب",
        "delete_book_confirm" to "هل أنت متأكد من رغبتك في إزالة هذا الكتاب من مكتبتك؟",
        "cancel" to "إلغاء",
        "delete" to "حذف",
        "filter_all" to "كافة الصيغ",
        "filter_pdf" to "PDF",
        "filter_epub" to "EPUB",
        "filter_txt" to "TXT",
        "sort_recent" to "المقروء مؤخراً",
        "sort_title" to "العنوان (أ - ي)",
        "sort_progress" to "الأعلى تقدماً",

        // Settings & Storage
        "language_title" to "لغة التطبيق",
        "language_desc" to "اختر لغة العرض المفضلة لديك داخل التطبيق.",
        "storage_title" to "المساحة وقاعدة البيانات",
        "installed_books" to "الكتب المثبتة بالمكتبة",
        "saved_highlights" to "إجمالي الاقتباسات المحفوظة",
        "offline_cache" to "ذاكرة التخزين المحلية المؤقتة",
        "features_title" to "الميزات المضمنة",
        "speed_reader" to "القراءة السريعة RSVP",
        "ai_assistant" to "مساعد القراءة الذكي",
        "reading_streak" to "سلسلة القراءة A-HEX",
        "active_habit" to "عادة نشطة",
        "open_in_browser" to "بحث على الإنترنت",
        "direct_pdf_download" to "تحميل PDF",
        "trusted_badge" to "مصدر معتمد ومرخص للقراءة الحرة",
        "reading_mode" to "نمط القراءة",
        "mode_light" to "نهاري (فاتح)",
        "mode_sepia" to "سيبيا (داكن مريح)",
        "mode_dark" to "ليلي (مظلم)",
        "theme_palette" to "نسق الألوان",
        "daily_goal_title" to "هدف القراءة اليومي",
        "daily_goal_desc" to "حدد دقائق القراءة اليومية المستهدفة لبناء واستمرار سلسلتك اليومية.",
        "export_backup" to "تصدير نسخة احتياطية",
        "restore_backup" to "استعادة نسخة احتياطية",
        "share_progress" to "مشاركة التقدم",
        "streak_zero_title" to "جاهز لبدء سلسلتك القرائية!",
        "streak_zero_desc" to "اقرأ اليوم للبدء في أول يوم من سلسلة قراءتك اليومية.",

        // TTS & Audio
        "tts_title" to "القارئ الصوتي الآلي (TTS)",
        "tts_initializing" to "جاري تهيئة محرك الصوت...",
        "tts_ready" to "المحرك الصوتي جاهز",
        "tts_playing" to "جاري القراءة بصوت عالٍ...",
        "tts_paused" to "تم إيقاف القراءة مؤقتاً",
        "tts_unsupported" to "اللغة غير مدعومة في محرك الصوت الحالي.",
        "tts_missing_data" to "بيانات الصوت العربي غير مثبتة بالجهاز. يرجى تنزيلها من إعدادات Android.",
        "tts_open_settings" to "فتح إعدادات الصوت TTS",
        "tts_error" to "خطأ في تشغيل الصوت",
        "tts_speed" to "سرعة القراءة",

        // RSVP Speed Reader
        "rsvp_title" to "القراءة السريعة RSVP",
        "rsvp_wpm" to "كلمة/دقيقة",
        "rsvp_word_count" to "الكلمة %1\$d من %2\$d",
        "rsvp_time_left" to "متبقي ~%1\$s",
        "rsvp_back_20" to "تراجع 20 كلمة",
        "rsvp_forward_20" to "تقدم 20 كلمة",
        "rsvp_page" to "ص %1\$d/%2\$d",

        // Smart Face Presence Counter (Privacy-First)
        "face_presence_title" to "حساب القراءة الذكي بحضور الوجه",
        "face_presence_desc" to "حساب فترات القراءة فقط عند تواجد وانتباه الوجه نحو الشاشة. لا يتم حفظ صور أو نقل أي بيانات خارج جهازك نهائياً.",
        "face_presence_enabled" to "تتبع حضور الوجه مفعل",
        "face_presence_attentive" to "قراءة نشطة (تم رصد الوجه)",
        "face_presence_candidate" to "جاري رصد الوجه...",
        "face_presence_no_face" to "الوجه غير متواجد (مؤقت متوقف)",
        "face_presence_multi_faces" to "تم رصد أكثر من وجه",
        "face_presence_permission_required" to "يتطلب إذن الكاميرا لتفعيل التتبع الذكي لوقت القراءة.",
        "face_presence_camera_unavailable" to "الكاميرا غير متوفرة حالياً",
        "face_presence_disclaimer" to "ملاحظة: يقدر التواجد الفعلي للشخص فقط ولا يعتبر مقياساً دقيقاً للاستيعاب القرائي.",
        "face_privacy_badge" to "100% معالجة محلية بدون حفظ أي صور",

        // Custom Voice Narrator Profile
        "voice_narrator_title" to "استوديو الراوي الصوتي المخصص",
        "voice_narrator_desc" to "أنشئ ملفك الصوتي الخاص لقراءة الكتب بصوتك وبنبرتك وسرعتك المفضلة.",
        "voice_narrator_train_btn" to "تسجيل وتدريب الراوي الصوتي",
        "voice_narrator_active" to "الصوت المخصص مفعل",
        "voice_narrator_system" to "صوت النظام مفعل",

        // PDF Extraction Quality
        "pdf_scanned_notice" to "مستند مصور / ماسح ضوئي: قد تكون وظائف النص (الصوت، RSVP، البحث) محدودة.",
        "pdf_high_quality" to "مستند PDF نصي قابل للبحث",

        // Common Reader Actions
        "chapter_toc" to "فهرس الفصول",
        "notes_and_highlights" to "الملاحظات والاقتباسات",
        "font_size" to "حجم الخط",
        "line_spacing" to "تباعد الأسطر",
        "export_epub" to "تحويل وتصدير EPUB",
        "ambient_sounds" to "أصوات القراءة المهدئة",
        "vocab_vault" to "خزينة المفردات",
        "mind_map" to "الخريطة الذهنية للفصل",
        "book_reviews" to "المراجعات والنقاشات",

        // Interactive Onboarding & Tutorial
        "onboarding_skip" to "تخطي",
        "onboarding_next" to "التالي",
        "onboarding_back" to "السابق",
        "onboarding_get_started" to "بدء رحلة القراءة",
        "onboarding_start_tutorial" to "جولة تعريفية تفاعلية",
        "onboarding_welcome_title" to "عزز عادة قراءتك اليومية",
        "onboarding_welcome_subtitle" to "قارئ إلكتروني متكامل وخالٍ من المشتتات، يعمل 100% بدون إنترنت لبناء سلاسل قراءة مستمرة لكتب PDF وEPUB وTXT.",
        "onboarding_habit_title" to "حدد هدف القراءة اليومي",
        "onboarding_habit_subtitle" to "اختر هدفك اليومي بالدقائق. الجلسات اليومية المنتظمة تتراكم لتصل إلى عشرات الكتب سنوياً.",
        "onboarding_features_title" to "جرّب الأدوات التفاعلية",
        "onboarding_features_subtitle" to "جرّب القارئ السريع RSVP، وأنماط القراءة المريحة، والراوي الصوتي الآن.",
        "onboarding_genres_title" to "اختر اهتماماتك الأدبية",
        "onboarding_genres_subtitle" to "خصص رف كتبك المبدئي حسب التصنيفات التي تفضل قراءتها.",
        "tutorial_title" to "جولة تفاعلية",
        "tutorial_step1_title" to "المكتبة الشاملة",
        "tutorial_step1_desc" to "تصفح واقرأ كتب EPUB وPDF وTXT محلياً. استخدم الفلترة والبحث واستورد كتبك بسهولة.",
        "tutorial_step2_title" to "سلسلة القراءة والتحديات",
        "tutorial_step2_desc" to "كل دقيقة قراءة تحسب ضمن سلسلتك اليومية. احصل على دروع الحماية وأنجز مهام القراءة.",
        "tutorial_step3_title" to "القراءة السريعة والقارئ الصوتي",
        "tutorial_step3_desc" to "زد من سرعة قراءتك بتقنية RSVP أو استمع لكتبك بصوت طبيعي مريح.",
        "tutorial_step4_title" to "استوديو الصوت والخصوصية",
        "tutorial_step4_desc" to "أنشئ ملفك الصوتي الخاص لقراءة الكتب بصوتك. معالجة 100% داخل جهازك دون رفع أي بيانات.",
        "settings_replay_onboarding" to "إعادة تشغيل شاشات الترحيب",
        "settings_replay_tutorial" to "جولة الميزات التفاعلية"
    )

    private val frenchStrings = mapOf(
        "app_name" to "A-Hex streak",
        "tab_library" to "Bibliothèque",
        "tab_local_space" to "Espace Local",
        "tab_streak" to "Série",
        "tab_highlights" to "Extraits",
        "tab_discover" to "Découvrir",
        "tab_settings" to "Paramètres",

        // Search & Library
        "search_hint" to "Rechercher livres, auteurs, genres...",
        "search_trusted_title" to "Recherche en ligne (Noor Book & Gutenberg)",
        "search_trusted_desc" to "Recherchez sur www.noor-book.com pour les livres arabes et sur https://www.gutenberg.org/ pour les classiques en anglais.",
        "search_noor_book" to "Noor Book (noor-book.com)",
        "search_gutenberg" to "Projet Gutenberg (gutenberg.org)",
        "import_book" to "Importer un document",
        "import_book_desc" to "Ajouter des livres EPUB, PDF ou TXT depuis la mémoire locale",
        "empty_library_title" to "Votre bibliothèque est vide",
        "empty_library_desc" to "Appuyez ci-dessous pour importer vos fichiers EPUB, PDF ou TXT, ou explorez nos classiques.",
        "explore_catalog" to "Explorer le catalogue",
        "delete_book" to "Supprimer le livre",
        "delete_book_confirm" to "Êtes-vous sûr de vouloir retirer ce livre de votre bibliothèque ?",
        "cancel" to "Annuler",
        "delete" to "Supprimer",
        "filter_all" to "Tous formats",
        "filter_pdf" to "PDF",
        "filter_epub" to "EPUB",
        "filter_txt" to "TXT",
        "sort_recent" to "Lus récemment",
        "sort_title" to "Titre (A-Z)",
        "sort_progress" to "Meilleure progression",

        // Settings & Storage
        "language_title" to "Langue de l'application",
        "language_desc" to "Sélectionnez votre langue d'affichage préférée.",
        "storage_title" to "Stockage et base de données",
        "installed_books" to "Livres installés en bibliothèque",
        "saved_highlights" to "Total des passages surlignés",
        "offline_cache" to "Cache local hors-ligne",
        "features_title" to "Fonctionnalités incluses",
        "speed_reader" to "Lecteur rapide RSVP",
        "ai_assistant" to "Assistant de lecture intelligent",
        "reading_streak" to "SÉRIE DE LECTURE A-HEX",
        "active_habit" to "Habitude active",
        "open_in_browser" to "Rechercher en ligne",
        "direct_pdf_download" to "Télécharger le PDF",
        "trusted_badge" to "Domaine public vérifié et accès libre",
        "reading_mode" to "Mode de lecture",
        "mode_light" to "Clair",
        "mode_sepia" to "Sépia",
        "mode_dark" to "Sombre",
        "theme_palette" to "Palette de thème",
        "daily_goal_title" to "Objectif de lecture quotidien",
        "daily_goal_desc" to "Définissez votre objectif de lecture quotidien en minutes pour maintenir votre série.",
        "export_backup" to "Exporter la sauvegarde",
        "restore_backup" to "Restaurer la sauvegarde",
        "share_progress" to "Partager la progression",
        "streak_zero_title" to "Prêt à commencer votre série !",
        "streak_zero_desc" to "Lisez aujourd'hui pour démarrer votre premier jour de série.",

        // TTS & Audio
        "tts_title" to "Lecture vocale (TTS)",
        "tts_initializing" to "Initialisation du moteur vocal...",
        "tts_ready" to "Moteur vocal prêt",
        "tts_playing" to "Lecture vocale en cours...",
        "tts_paused" to "Lecture en pause",
        "tts_unsupported" to "Langue non supportée par le moteur TTS actuel.",
        "tts_missing_data" to "Données vocales manquantes. Téléchargez-les dans les paramètres Android.",
        "tts_open_settings" to "Ouvrir les paramètres TTS",
        "tts_error" to "Erreur de lecture TTS",
        "tts_speed" to "Vitesse vocale",

        // RSVP Speed Reader
        "rsvp_title" to "Lecteur rapide RSVP",
        "rsvp_wpm" to "Mots/min",
        "rsvp_word_count" to "Mot %1\$d sur %2\$d",
        "rsvp_time_left" to "~%1\$s restant",
        "rsvp_back_20" to "Reculer de 20 mots",
        "rsvp_forward_20" to "Avancer de 20 mots",
        "rsvp_page" to "Page %1\$d/%2\$d",

        // Smart Face Presence Counter (Privacy-First)
        "face_presence_title" to "Détection de présence de lecture",
        "face_presence_desc" to "Comptabilisation du temps de lecture uniquement quand votre visage est attentif. Aucune image enregistrée ou transmise.",
        "face_presence_enabled" to "Détection de présence activée",
        "face_presence_attentive" to "Lecture active (Visage détecté)",
        "face_presence_candidate" to "Recherche du visage...",
        "face_presence_no_face" to "Visage absent (Chronomètre en pause)",
        "face_presence_multi_faces" to "Plusieurs visages détectés",
        "face_presence_permission_required" to "Autorisation caméra requise pour le suivi de présence.",
        "face_presence_camera_unavailable" to "Caméra indisponible",
        "face_presence_disclaimer" to "Note : Estime uniquement l'attention physique devant l'écran, sans mesurer la compréhension.",
        "face_privacy_badge" to "100% sur l'appareil & Zéro stockage d'images",

        // Custom Voice Narrator Profile
        "voice_narrator_title" to "Studio du Narrateur Vocal Personnalisé",
        "voice_narrator_desc" to "Créez votre profil vocal personnalisé pour écouter vos livres avec votre propre timbre, cadence et intonation.",
        "voice_narrator_train_btn" to "Enregistrer et créer mon profil vocal",
        "voice_narrator_active" to "Voix personnalisée active",
        "voice_narrator_system" to "Voix système active",

        // PDF Extraction Quality
        "pdf_scanned_notice" to "Document numérisé / image : les fonctions texte (TTS, RSVP, recherche) peuvent être limitées.",
        "pdf_high_quality" to "Document PDF texte indexable",

        // Common Reader Actions
        "chapter_toc" to "Table des matières",
        "notes_and_highlights" to "Notes et surlignages",
        "font_size" to "Taille de police",
        "line_spacing" to "Espacement des lignes",
        "export_epub" to "Convertir et exporter en EPUB",
        "ambient_sounds" to "Ambiances sonores relaxantes",
        "vocab_vault" to "Coffre de vocabulaire",
        "mind_map" to "Carte mentale du chapitre",
        "book_reviews" to "Avis et discussions",

        // Interactive Onboarding & Tutorial
        "onboarding_skip" to "Passer",
        "onboarding_next" to "Suivant",
        "onboarding_back" to "Retour",
        "onboarding_get_started" to "Démarrer l'aventure",
        "onboarding_start_tutorial" to "Lancer la visite guidée",
        "onboarding_welcome_title" to "Boostez votre lecture quotidienne",
        "onboarding_welcome_subtitle" to "La liseuse sans distraction, 100% hors-ligne, conçue pour forger des séries de lecture durables sur PDF, EPUB et TXT.",
        "onboarding_habit_title" to "Définissez votre habitude",
        "onboarding_habit_subtitle" to "Fixez votre objectif quotidien en minutes. De petites sessions régulières se transforment en dizaines de livres par an.",
        "onboarding_features_title" to "Outils de lecture interactifs",
        "onboarding_features_subtitle" to "Testez dès maintenant le lecteur rapide RSVP, les thèmes de lecture et le narrateur vocal personnalisé.",
        "onboarding_genres_title" to "Vos univers littéraires",
        "onboarding_genres_subtitle" to "Personnalisez votre étagère de départ avec vos genres préférés.",
        "tutorial_title" to "Visite guidée interactive",
        "tutorial_step1_title" to "Bibliothèque universelle",
        "tutorial_step1_desc" to "Lisez vos fichiers EPUB, PDF et TXT hors-ligne. Filtrez, recherchez et importez vos documents en un clic.",
        "tutorial_step2_title" to "Série A-Hex et Quêtes",
        "tutorial_step2_desc" to "Chaque minute de lecture attentive alimente votre série. Gagnez des Boucliers et accomplissez des quêtes.",
        "tutorial_step3_title" to "Lecture rapide RSVP & Audio",
        "tutorial_step3_desc" to "Accélérez votre vitesse avec le défilement de mots RSVP, ou profitez de la lecture vocale naturelle.",
        "tutorial_step4_title" to "Studio Vocal & Confidentialité",
        "tutorial_step4_desc" to "Créez votre profil vocal personnalisé. 100% exécuté sur l'appareil sans transmission de données.",
        "settings_replay_onboarding" to "Revoir l'introduction",
        "settings_replay_tutorial" to "Visite guidée interactive"
    )
}
